CREATE TABLE IF NOT EXISTS players (pid TEXT PRIMARY KEY, treats INTEGER NOT NULL DEFAULT 10, regen INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS slips (ref TEXT PRIMARY KEY, pid TEXT, amount REAL, at INTEGER);
